/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputTypes, MinMaxValue } from "./components/input/model";
export namespace Components {
    interface Co2Input {
        /**
          * HTML checked attribute
         */
        "isChecked"?: boolean;
        /**
          * HTML disabled attribute
         */
        "isDisabled"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        "maxLength"?: number;
        "maxValue"?: MinMaxValue;
        "minLength"?: number;
        "minValue"?: MinMaxValue;
        /**
          * HTML name attribute
         */
        "name"?: string;
        "type"?: InputTypes;
        /**
          * HTML value attribute
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCo2InputElement extends Components.Co2Input, HTMLStencilElement {
    }
    var HTMLCo2InputElement: {
        prototype: HTMLCo2InputElement;
        new (): HTMLCo2InputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "co2-input": HTMLCo2InputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Co2Input {
        /**
          * HTML checked attribute
         */
        "isChecked"?: boolean;
        /**
          * HTML disabled attribute
         */
        "isDisabled"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        "maxLength"?: number;
        "maxValue"?: MinMaxValue;
        "minLength"?: number;
        "minValue"?: MinMaxValue;
        /**
          * HTML name attribute
         */
        "name"?: string;
        /**
          * HTML onBlur event
         */
        "onScaleBlur"?: (event: CustomEvent<FocusEvent>) => void;
        /**
          * HTML onChange|onInput events (depending on type)
         */
        "onScaleChange"?: (event: CustomEvent<InputEvent>) => void;
        "type"?: InputTypes;
        /**
          * HTML value attribute
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "co2-input": Co2Input;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "co2-input": LocalJSX.Co2Input & JSXBase.HTMLAttributes<HTMLCo2InputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
