/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Co2Input {
        /**
          * The label
         */
        "disabled": boolean;
        /**
          * The label
         */
        "label": string;
        /**
          * The name
         */
        "name": string;
        "type"?: 'email' | 'hidden' | 'number' | 'password' | 'tel' | 'text' | 'checkbox' | 'radio' | 'url';
        /**
          * The value
         */
        "value"?: string;
    }
    interface Co2Label {
        /**
          * The text
         */
        "text": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCo2InputElement extends Components.Co2Input, HTMLStencilElement {
    }
    var HTMLCo2InputElement: {
        prototype: HTMLCo2InputElement;
        new (): HTMLCo2InputElement;
    };
    interface HTMLCo2LabelElement extends Components.Co2Label, HTMLStencilElement {
    }
    var HTMLCo2LabelElement: {
        prototype: HTMLCo2LabelElement;
        new (): HTMLCo2LabelElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "co2-input": HTMLCo2InputElement;
        "co2-label": HTMLCo2LabelElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Co2Input {
        /**
          * The label
         */
        "disabled"?: boolean;
        /**
          * The label
         */
        "label"?: string;
        /**
          * The name
         */
        "name"?: string;
        /**
          * The onChange
         */
        "onScaleChange"?: (event: CustomEvent<InputEvent>) => void;
        "type"?: 'email' | 'hidden' | 'number' | 'password' | 'tel' | 'text' | 'checkbox' | 'radio' | 'url';
        /**
          * The value
         */
        "value"?: string;
    }
    interface Co2Label {
        /**
          * The text
         */
        "text"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "co2-input": Co2Input;
        "co2-label": Co2Label;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "co2-input": LocalJSX.Co2Input & JSXBase.HTMLAttributes<HTMLCo2InputElement>;
            "co2-label": LocalJSX.Co2Label & JSXBase.HTMLAttributes<HTMLCo2LabelElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
